-- CREATE DATABASE board;
-- 
-- USE board;
-- 
-- CREATE TABLE board_info(
-- 	board_no INT PRIMARY KEY AUTO_INCREMENT NOT NULL
-- 	,board_title VARCHAR(100) NOT NULL
-- 	,board_contents VARCHAR(1000) NOT NULL
-- 	,board_write_date DATETIME NOT NULL
-- 	,board_del_flg CHAR(1) NOT NULL DEFAULT('0')
-- 	,board_del_date DATETIME
-- );
-- 
-- DESC board_info
-- 
-- INSERT INTO board_info(
-- 	board_title 
-- 	,board_contents
--  	,board_write_date 
-- )
-- VALUES ('제목21','내용21',NOW()),('제목22','내용22',NOW()),('제목23','내용23',NOW()),('제목24','내용24',NOW())
-- 		,('제목25','내용25',NOW()),('제목26','내용26',NOW()),('제목27','내용27',NOW()),('제목28','내용28',NOW())
-- 		,('제목29','내용29',NOW()),('제목30','내용30',NOW());

-- SELECT * FROM board_info;
-- 
COMMIT;
-- 
-- SELECT
-- 	board_title 
-- 	,board_contents
--  	,board_write_date  
-- FROM 
-- 	board_info
-- WHERE 
-- 	board_del_flg = '0'
-- ORDER BY 
-- 	board_no ASC
-- limit 5 OFFSET 0
-- ;

SELECT COUNT(board_no) FROM board_info WHERE board_del_flg = '0'